# Generated by Django 2.1.15 on 2020-08-03 19:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DBNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(default='', max_length=254)),
                ('Status', models.BooleanField(default=True)),
                ('internal_hostname', models.CharField(default='', max_length=16)),
                ('external_hostname', models.CharField(default='', max_length=16)),
                ('db_engine', models.CharField(default='', max_length=16)),
                ('db_version', models.CharField(default='', max_length=16)),
                ('db_load_type', models.CharField(default='', max_length=16)),
                ('user_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Deleted_Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(default='', max_length=128)),
                ('user_id', models.CharField(default='', max_length=128)),
                ('email', models.EmailField(default='', max_length=254)),
                ('instance_type', models.CharField(default='', max_length=16)),
                ('date_deleted', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_ID', models.CharField(default='', max_length=256)),
                ('Email', models.EmailField(default='', max_length=254)),
                ('Status', models.BooleanField()),
                ('Name', models.CharField(max_length=32)),
                ('Framework', models.CharField(default='', max_length=32)),
                ('Date_Created', models.DateTimeField(default=django.utils.timezone.now)),
                ('Load_Type', models.CharField(default='', max_length=16)),
                ('order_node_count', models.IntegerField(default=0)),
                ('db_link', models.BooleanField(default=False)),
                ('is_webapp', models.BooleanField(default=False)),
                ('IPv4', models.CharField(default='', max_length=16)),
                ('Private_IPv4', models.CharField(default='', max_length=16)),
                ('Domain_Name', models.CharField(default='', max_length=128)),
                ('Subdomain', models.CharField(default='', max_length=128)),
                ('Monitoring', models.CharField(default='', max_length=128)),
                ('user_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Purchases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='', max_length=254)),
                ('purchase_id', models.CharField(default='', max_length=256)),
                ('user_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserTrait',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='', max_length=254, unique=True)),
                ('credit_card_number', models.CharField(default='', max_length=64)),
                ('credit_card_holder_name', models.CharField(default='', max_length=64)),
                ('credit_card_expire_month', models.CharField(default='', max_length=12)),
                ('credit_card_expire_year', models.CharField(default='', max_length=12)),
                ('credit_card_security_code', models.CharField(default='', max_length=64)),
                ('low_nodes_count', models.IntegerField(default=0)),
                ('medium_nodes_count', models.IntegerField(default=0)),
                ('high_nodes_count', models.IntegerField(default=0)),
                ('web_app_nodes_active', models.IntegerField(default=0)),
                ('db_nodes_active', models.IntegerField(default=0)),
                ('order_price_beginning', models.IntegerField(default=0)),
                ('total_billing_history', models.IntegerField(default=0)),
                ('order_count', models.IntegerField(default=0)),
                ('monthly_billing', models.IntegerField(default=0)),
                ('deleted_nodes_history', models.IntegerField(default=0)),
                ('user_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
