# Generated by Django 2.1.15 on 2020-08-03 21:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbnode',
            name='Date_Created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='dbnode',
            name='db_uid',
            field=models.CharField(default='', max_length=256),
        ),
    ]
