# Generated by Django 2.1.15 on 2020-08-03 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20200803_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='linked_to_db_uuid',
            field=models.CharField(default='', max_length=256),
        ),
    ]
