# Generated by Django 2.1.15 on 2020-08-03 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_node_linked_to_db_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='db_link',
        ),
    ]
