# Generated by Django 2.1.15 on 2020-08-03 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_remove_node_db_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbnode',
            name='id_link_color',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='node',
            name='id_link_color',
            field=models.CharField(default='', max_length=10),
        ),
    ]
