# Generated by Django 2.1.15 on 2020-08-03 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20200803_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='framework_version',
            field=models.CharField(default='', max_length=256),
        ),
    ]
