# Generated by Django 2.1.15 on 2020-08-04 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20200803_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbnode',
            name='linked_to_node_uuid',
            field=models.CharField(default='', max_length=256),
        ),
    ]
