# Generated by Django 2.1.15 on 2020-08-05 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_dbnode_linked_to_node_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='server_region',
            field=models.CharField(default='', max_length=32),
        ),
    ]
