# Generated by Django 2.1.15 on 2020-08-05 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20200805_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbnode',
            name='db_name',
            field=models.CharField(default='', max_length=256),
        ),
    ]
