# Generated by Django 2.1.15 on 2020-08-05 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_dbnode_db_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dbnode',
            old_name='external_hostname',
            new_name='db_hostname',
        ),
        migrations.RemoveField(
            model_name='dbnode',
            name='internal_hostname',
        ),
    ]
