# Generated by Django 2.1.15 on 2020-08-05 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20200805_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbnode',
            name='db_hostname',
            field=models.CharField(default='', max_length=256),
        ),
    ]
