# Generated by Django 2.1.15 on 2020-08-10 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_auto_20200805_0136'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertrait',
            name='dbms_password',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='usertrait',
            name='dbms_username',
            field=models.CharField(default='', max_length=64),
        ),
    ]
