# Generated by Django 2.1.15 on 2020-08-10 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_auto_20200810_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertrait',
            name='dbms_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
