# Generated by Django 3.0.7 on 2020-08-25 21:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0018_auto_20200811_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='', max_length=254)),
                ('Date_Uploaded', models.DateTimeField(default=django.utils.timezone.now)),
                ('file_name', models.CharField(default='', max_length=128)),
                ('user_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
