# Generated by Django 3.0.7 on 2020-08-25 22:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_auto_20200825_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedproject',
            name='file_size',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='uploadedproject',
            name='linked_to_node_uuid',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='dbnode',
            name='Date_Created',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 25, 22, 30, 59, 676520)),
        ),
        migrations.AlterField(
            model_name='deleted_node',
            name='date_deleted',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 25, 22, 30, 59, 677945)),
        ),
        migrations.AlterField(
            model_name='node',
            name='Date_Created',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 25, 22, 30, 59, 677242)),
        ),
        migrations.AlterField(
            model_name='uploadedproject',
            name='Date_Uploaded',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 25, 22, 30, 59, 674797)),
        ),
    ]
