# Generated by Django 3.0.7 on 2020-08-26 10:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_auto_20200825_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedproject',
            name='file_system_name',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='dbnode',
            name='Date_Created',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 26, 10, 4, 44, 939364)),
        ),
        migrations.AlterField(
            model_name='deleted_node',
            name='date_deleted',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 26, 10, 4, 44, 941028)),
        ),
        migrations.AlterField(
            model_name='node',
            name='Date_Created',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 26, 10, 4, 44, 940211)),
        ),
        migrations.AlterField(
            model_name='uploadedproject',
            name='Date_Uploaded',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 26, 10, 4, 44, 937234)),
        ),
    ]
