# Generated by Django 3.0.7 on 2020-08-26 23:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_auto_20200826_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='linked_to_project',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dbnode',
            name='Date_Created',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 26, 23, 32, 7, 923888)),
        ),
        migrations.AlterField(
            model_name='deleted_node',
            name='date_deleted',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 26, 23, 32, 7, 925295)),
        ),
        migrations.AlterField(
            model_name='node',
            name='Date_Created',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 26, 23, 32, 7, 924612)),
        ),
        migrations.AlterField(
            model_name='uploadedproject',
            name='Date_Uploaded',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 26, 23, 32, 7, 922041)),
        ),
    ]
