# Generated by Django 3.0.7 on 2020-08-28 11:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_auto_20200826_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='projet_link_uuid',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='dbnode',
            name='Date_Created',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 28, 11, 14, 31, 968513)),
        ),
        migrations.AlterField(
            model_name='deleted_node',
            name='date_deleted',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 28, 11, 14, 31, 969887)),
        ),
        migrations.AlterField(
            model_name='node',
            name='Date_Created',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 28, 11, 14, 31, 969208)),
        ),
        migrations.AlterField(
            model_name='uploadedproject',
            name='Date_Uploaded',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 28, 11, 14, 31, 966738)),
        ),
    ]
