# Generated by Django 3.0.7 on 2020-08-28 20:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_auto_20200828_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbnode',
            name='external_hostname',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='dbnode',
            name='internal_hostname',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='dbnode',
            name='Date_Created',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 28, 20, 21, 3, 878513)),
        ),
        migrations.AlterField(
            model_name='deleted_node',
            name='date_deleted',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 28, 20, 21, 3, 879974)),
        ),
        migrations.AlterField(
            model_name='node',
            name='Date_Created',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 28, 20, 21, 3, 879313)),
        ),
        migrations.AlterField(
            model_name='uploadedproject',
            name='Date_Uploaded',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 28, 20, 21, 3, 876339)),
        ),
    ]
