# Generated by Django 2.1.11 on 2020-08-31 00:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_auto_20200828_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='exposed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dbnode',
            name='Date_Created',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 31, 0, 52, 54, 203202)),
        ),
        migrations.AlterField(
            model_name='deleted_node',
            name='date_deleted',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 31, 0, 52, 54, 205024)),
        ),
        migrations.AlterField(
            model_name='node',
            name='Date_Created',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 31, 0, 52, 54, 204124)),
        ),
        migrations.AlterField(
            model_name='uploadedproject',
            name='Date_Uploaded',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 31, 0, 52, 54, 201170)),
        ),
    ]
