# Generated by Django 2.1.11 on 2020-09-20 12:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_auto_20200920_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbnode',
            name='Date_Created',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 20, 12, 55, 47, 699149, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='deleted_node',
            name='date_deleted',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 20, 12, 55, 47, 700954, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='node',
            name='Date_Created',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 20, 12, 55, 47, 700048, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='uploadedproject',
            name='Date_Uploaded',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 20, 12, 55, 47, 697136, tzinfo=utc)),
        ),
    ]
