# Generated by Django 2.2.16 on 2020-11-30 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0033_auto_20200920_1256'),
        ('dashboard', '0019_auto_20200818_2147'),
    ]

    operations = [
    ]
