# Generated by Django 3.1.1 on 2020-12-07 12:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0037_auto_20201207_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertrait',
            name='unique_id',
            field=models.CharField(default='8b1071d0286b4bc2a9f67459e8d61ce9', max_length=64),
        ),
        migrations.AlterField(
            model_name='dbnode',
            name='Date_Created',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 7, 12, 59, 55, 292268)),
        ),
        migrations.AlterField(
            model_name='deleted_node',
            name='date_deleted',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 7, 12, 59, 55, 294141)),
        ),
        migrations.AlterField(
            model_name='node',
            name='Date_Created',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 7, 12, 59, 55, 293221)),
        ),
        migrations.AlterField(
            model_name='uploadedproject',
            name='Date_Uploaded',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 7, 12, 59, 55, 290181)),
        ),
    ]
