# Generated by Django 3.1.1 on 2020-12-07 13:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0038_auto_20201207_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbnode',
            name='Date_Created',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 7, 13, 5, 6, 787272)),
        ),
        migrations.AlterField(
            model_name='deleted_node',
            name='date_deleted',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 7, 13, 5, 6, 789133)),
        ),
        migrations.AlterField(
            model_name='node',
            name='Date_Created',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 7, 13, 5, 6, 788215)),
        ),
        migrations.AlterField(
            model_name='uploadedproject',
            name='Date_Uploaded',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 7, 13, 5, 6, 785218)),
        ),
        migrations.AlterField(
            model_name='usertrait',
            name='unique_id',
            field=models.CharField(default='', max_length=64),
        ),
    ]
