# Generated by Django 3.1.1 on 2020-12-08 23:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0039_auto_20201207_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbnode',
            name='Date_Created',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 8, 23, 32, 0, 267486)),
        ),
        migrations.AlterField(
            model_name='deleted_node',
            name='date_deleted',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 8, 23, 32, 0, 269322)),
        ),
        migrations.AlterField(
            model_name='node',
            name='Date_Created',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 8, 23, 32, 0, 268473)),
        ),
        migrations.AlterField(
            model_name='uploadedproject',
            name='Date_Uploaded',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 8, 23, 32, 0, 264921)),
        ),
        migrations.CreateModel(
            name='api_serivce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='', max_length=254)),
                ('date_created', models.DateTimeField(default=datetime.datetime(2020, 12, 8, 23, 32, 0, 266023))),
                ('aws_account_id', models.CharField(default='', max_length=12)),
                ('aws_access_key', models.CharField(default='', max_length=20)),
                ('aws_secret_key', models.CharField(default='', max_length=40)),
                ('user_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
