# Generated by Django 3.1.1 on 2020-12-08 23:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0040_auto_20201208_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='api_serivce',
            name='api_id',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='api_serivce',
            name='cloud_provider',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='api_serivce',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 8, 23, 37, 49, 399306)),
        ),
        migrations.AlterField(
            model_name='dbnode',
            name='Date_Created',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 8, 23, 37, 49, 400804)),
        ),
        migrations.AlterField(
            model_name='deleted_node',
            name='date_deleted',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 8, 23, 37, 49, 402664)),
        ),
        migrations.AlterField(
            model_name='node',
            name='Date_Created',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 8, 23, 37, 49, 401797)),
        ),
        migrations.AlterField(
            model_name='uploadedproject',
            name='Date_Uploaded',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 8, 23, 37, 49, 398204)),
        ),
    ]
