# Generated by Django 3.1.1 on 2020-12-09 00:03

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0041_auto_20201208_2337'),
    ]

    operations = [
        migrations.CreateModel(
            name='api_service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='', max_length=254)),
                ('date_created', models.DateTimeField(default=datetime.datetime(2020, 12, 9, 0, 3, 10, 811504))),
                ('aws_account_id', models.CharField(default='', max_length=12)),
                ('aws_access_key', models.CharField(default='', max_length=20)),
                ('aws_secret_key', models.CharField(default='', max_length=40)),
                ('api_id', models.CharField(default='', max_length=10)),
                ('cloud_provider', models.CharField(default='', max_length=30)),
                ('user_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='uploadedproject',
            old_name='email',
            new_name='email_to_report',
        ),
        migrations.AddField(
            model_name='uploadedproject',
            name='owner_email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='dbnode',
            name='Date_Created',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 9, 0, 3, 10, 812988)),
        ),
        migrations.AlterField(
            model_name='deleted_node',
            name='date_deleted',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 9, 0, 3, 10, 814834)),
        ),
        migrations.AlterField(
            model_name='node',
            name='Date_Created',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 9, 0, 3, 10, 813975)),
        ),
        migrations.AlterField(
            model_name='uploadedproject',
            name='Date_Uploaded',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 9, 0, 3, 10, 810391)),
        ),
        migrations.DeleteModel(
            name='api_serivce',
        ),
    ]
