# Generated by Django 3.1.1 on 2020-12-09 00:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0042_auto_20201209_0003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='api_service',
            old_name='email',
            new_name='email_to_report',
        ),
        migrations.AddField(
            model_name='api_service',
            name='owner_email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='api_service',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 9, 0, 10, 8, 971505)),
        ),
        migrations.AlterField(
            model_name='dbnode',
            name='Date_Created',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 9, 0, 10, 8, 973019)),
        ),
        migrations.AlterField(
            model_name='deleted_node',
            name='date_deleted',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 9, 0, 10, 8, 974881)),
        ),
        migrations.AlterField(
            model_name='node',
            name='Date_Created',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 9, 0, 10, 8, 974014)),
        ),
        migrations.AlterField(
            model_name='uploadedproject',
            name='Date_Uploaded',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 9, 0, 10, 8, 970360)),
        ),
    ]
