# Generated by Django 3.1.1 on 2020-12-09 23:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0044_auto_20201209_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api_service',
            name='aws_access_key',
            field=models.CharField(default='', max_length=22),
        ),
        migrations.AlterField(
            model_name='api_service',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 9, 23, 55, 3, 272857)),
        ),
        migrations.AlterField(
            model_name='dbnode',
            name='Date_Created',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 9, 23, 55, 3, 274420)),
        ),
        migrations.AlterField(
            model_name='deleted_node',
            name='date_deleted',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 9, 23, 55, 3, 276300)),
        ),
        migrations.AlterField(
            model_name='node',
            name='Date_Created',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 9, 23, 55, 3, 275423)),
        ),
        migrations.AlterField(
            model_name='uploadedproject',
            name='Date_Uploaded',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 9, 23, 55, 3, 271698)),
        ),
    ]
