# Generated by Django 3.1.1 on 2020-12-13 07:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0047_auto_20201209_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api_service',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 13, 7, 24, 37, 665919)),
        ),
        migrations.AlterField(
            model_name='dbnode',
            name='Date_Created',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 13, 7, 24, 37, 667516)),
        ),
        migrations.AlterField(
            model_name='deleted_node',
            name='date_deleted',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 13, 7, 24, 37, 669310)),
        ),
        migrations.AlterField(
            model_name='node',
            name='Date_Created',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 13, 7, 24, 37, 668450)),
        ),
        migrations.AlterField(
            model_name='uploadedproject',
            name='Date_Uploaded',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 13, 7, 24, 37, 664794)),
        ),
        migrations.CreateModel(
            name='credit_card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_email', models.EmailField(default='', max_length=254)),
                ('date_created', models.DateTimeField(default=datetime.datetime(2020, 12, 13, 7, 24, 37, 664174))),
                ('card_number', models.IntegerField(default=0, max_length=16)),
                ('cvc_number', models.IntegerField(default=0, max_length=3)),
                ('zip_code', models.IntegerField(default=0, max_length=10)),
                ('address', models.CharField(default='', max_length=30)),
                ('country', models.CharField(default='', max_length=30)),
                ('name_on_card', models.CharField(default='', max_length=30)),
                ('user_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
