# Generated by Django 3.1.1 on 2020-12-13 08:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0048_auto_20201213_0724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api_service',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 13, 8, 3, 12, 623928)),
        ),
        migrations.AlterField(
            model_name='credit_card',
            name='card_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='credit_card',
            name='cvc_number',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='credit_card',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 13, 8, 3, 12, 622156)),
        ),
        migrations.AlterField(
            model_name='dbnode',
            name='Date_Created',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 13, 8, 3, 12, 626088)),
        ),
        migrations.AlterField(
            model_name='deleted_node',
            name='date_deleted',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 13, 8, 3, 12, 627960)),
        ),
        migrations.AlterField(
            model_name='node',
            name='Date_Created',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 13, 8, 3, 12, 627093)),
        ),
        migrations.AlterField(
            model_name='uploadedproject',
            name='Date_Uploaded',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 13, 8, 3, 12, 622790)),
        ),
    ]
