# Generated by Django 3.1.1 on 2020-12-13 08:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0049_auto_20201213_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api_service',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 13, 8, 4, 9, 967280)),
        ),
        migrations.AlterField(
            model_name='credit_card',
            name='card_number',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='credit_card',
            name='cvc_number',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='credit_card',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 13, 8, 4, 9, 965508)),
        ),
        migrations.AlterField(
            model_name='credit_card',
            name='zip_code',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='dbnode',
            name='Date_Created',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 13, 8, 4, 9, 968858)),
        ),
        migrations.AlterField(
            model_name='deleted_node',
            name='date_deleted',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 13, 8, 4, 9, 970678)),
        ),
        migrations.AlterField(
            model_name='node',
            name='Date_Created',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 13, 8, 4, 9, 969785)),
        ),
        migrations.AlterField(
            model_name='uploadedproject',
            name='Date_Uploaded',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 13, 8, 4, 9, 966242)),
        ),
    ]
