# Generated by Django 3.1.1 on 2020-12-13 10:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0051_auto_20201213_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit_card',
            name='card_uid',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='api_service',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 13, 10, 50, 18, 310069)),
        ),
        migrations.AlterField(
            model_name='credit_card',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 13, 10, 50, 18, 308205)),
        ),
        migrations.AlterField(
            model_name='dbnode',
            name='Date_Created',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 13, 10, 50, 18, 311712)),
        ),
        migrations.AlterField(
            model_name='deleted_node',
            name='date_deleted',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 13, 10, 50, 18, 313597)),
        ),
        migrations.AlterField(
            model_name='node',
            name='Date_Created',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 13, 10, 50, 18, 312694)),
        ),
        migrations.AlterField(
            model_name='uploadedproject',
            name='Date_Uploaded',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 13, 10, 50, 18, 308978)),
        ),
    ]
