# Generated by Django 3.1.1 on 2020-12-15 03:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0054_auto_20201215_0303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api_service',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 15, 3, 4, 50, 950905)),
        ),
        migrations.AlterField(
            model_name='credit_card',
            name='card_company',
            field=models.CharField(default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='credit_card',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 15, 3, 4, 50, 949233)),
        ),
        migrations.AlterField(
            model_name='dbnode',
            name='Date_Created',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 15, 3, 4, 50, 952438)),
        ),
        migrations.AlterField(
            model_name='deleted_node',
            name='date_deleted',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 15, 3, 4, 50, 954214)),
        ),
        migrations.AlterField(
            model_name='node',
            name='Date_Created',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 15, 3, 4, 50, 953330)),
        ),
        migrations.AlterField(
            model_name='transaction_messages',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 15, 3, 4, 50, 948669)),
        ),
        migrations.AlterField(
            model_name='uploadedproject',
            name='Date_Uploaded',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 15, 3, 4, 50, 949891)),
        ),
    ]
